#!/bin/sh

# script to help meshnodes make an autoupdate
# a node which looses connection (because a uplink mesh node is talking newer 
# batman v15) try to log in as client in a network with well known essid
# and forces a autoupdate (if it is turned on in general)
#
# this script do not do any harm if running for years
# more Info: https://github.com/viisauksena/gluon-v14tov15-helper

# some cron debug help , write in ram 
echo "v14v15 helper successfully startet at $(date +%y%m%d_%H%M)" > /tmp/v14_lastrun

# if your script is dependend on autoupdater, do only uptate if its realy enabled!
if [ $(uci get autoupdater.settings.enabled) = 0 ]; then exit 1; fi

# check gw
# quick and dirty do it 4 times every 30 seconds
# to prevent false positives
gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 11; fi ; sleep 30
gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 12; fi ; sleep 30 
gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 13; fi ; sleep 30 
gwl=$(batctl gwl -H |wc -l) ; if [ $gwl != 0 ]; then exit 14; fi

# if wlan0 is desired (only in configmode where we do not want autoupdater)
# ifconfig wlan0 up
# iw wlan0 connect freiburg.freifunk.net
# udhcp -b -i wlan0 

# check if freifunk as we know it is nearby
ffssid=$(uci get wireless.client_radio0.ssid)
: ${ffssid:=freiburg.freifunk.net} # if for whatever reason frssid is NULL
many=$(iwinfo phy0 scan |grep $ffssid | wc -l)

# connect to freifunk and get dhcp lease
if [ $many != 0 ]; then
	iw phy0 interface add update type managed
	ifconfig update up
	iw update connect $ffssid
	udhcpc -B -b -i update
fi

# just in case v6 dns resolving is strange
# something is wrong here .. if IFace is generated and all autoupdater /wget will throw v6 permission denied
cat /proc/sys/net/ipv6/conf/all/accept_ra > /tmp/accept_ra_tmp
cat /proc/sys/net/ipv6/conf/all/autoconf > /tmp/autoconf_tmp
echo 1 > /proc/sys/net/ipv6/conf/all/accept_ra
echo 1 > /proc/sys/net/ipv6/conf/all/autoconf

# just in case dns doesnt work , add extra foo
echo "nameserver 10.60.0.100" >> /etc/resolv.conf
echo "nameserver 4.2.2.2" >> /etc/resolv.conf

# here comes the funny part 
autoupdater -f

# if autoupdater and first checks above run correct you should never reach this point
# better safe than sorry - taking new IF down
iw update del
# do original v6 settings
cat /tmp/accept_ra_tmp > /proc/sys/net/ipv6/conf/all/accept_ra
cat /tmp/autoconf_tmp > /proc/sys/net/ipv6/conf/all/autoconf
# special exitcode
exit 21

